openapi: "3.0.1"
info:
  title: "swagger-api-dev"
  version: "v1.0"
servers:
- url: "https://1kg8f931ki.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /:
    get:
      summary: "List announcements"
      description: "Returns list of announcements"
      responses:
        500:
          description: "500 response"
          content: {}
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArrayOfAnnouncement"
    post:
      summary: "Create task"
      description: "Creates a new task"
      responses:
        400:
          description: "400 response"
          content: {}
        500:
          description: "500 response"
          content: {}
        201:
          description: "201 response"
          content: {}
    options:
      summary: "CORS support"
      responses:
        200:
          description: "Default response for CORS method"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  schemas:
    Announcement:
      type: "object"
      properties:
        announcementDes:
          type: "string"
        announceDate:
          type: "string"
        announcementName:
          type: "string"
        id:
          type: "string"
    ArrayOfAnnouncement:
      type: "array"
      items:
        $ref: "#/components/schemas/Announcement"
